development:
  adapter: postgresql
  encoding: unicode
  database: splittwo_development
  pool: 5
  username: petersaville
  password:
  timeout: 5000
  
test:
  adapter: postgresql
  encoding: unicode
  database: splittwo_test
  pool: 5
  username: petersaville
  password:
  timeout: 5000